<h3>Actions:</h3>
<ul>
	<li><a href="recreate_thumbnails.php">Recreate Thumbnails</a></li>
</ul>

<h3>Items:</h3>
<ul>
<?php foreach($configs AS $id => $Item): ?>
	<?php if( is_a($Item, 'ItemModel') ): ?>
		<li><a href="v-<?=$id?>">items/<?=$id?>.ini</a> (<a href="edit.php?id=<?=$id?>">Edit</a>): <?=($Item->hide)?' Hidden':'Published';?> <?=($Item->new)?'New':'';?></li>
	<?php else: ?>
		<li><a href="v-<?=$id?>">items/<?=$id?>.ini</a> (<a href="edit.php?id=<?=$id?>">Edit</a>): Error(<?=$Item?>)</li>
	<?php endif; ?>
<?php endforeach; ?>
</ul>