<p>
  &nbsp;&nbsp;
  <a href="http://twitter.com/share" class="twitter-share-button" data-count="horizontal" data-via="alesibaking" data-related="alesibaking" data-lang="es">Tweet</a><script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>
  <iframe src="http://www.facebook.com/plugins/like.php?href=http%3A%2F%2Falesibaking.com%2F&amp;send=true&amp;layout=button_count&amp;width=300&amp;show_faces=false&amp;action=like&amp;colorscheme=light&amp;font&amp;height=21" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:300px; height:21px;" allowTransparency="true"></iframe>
</p>
<?php foreach($Items AS $Item):?>
<div class="item">
	<h3><a href="v-<?=$Item->id?>"><?=$Item->name?></a></h3>
	<a href="v-<?=$Item->id?>"><img alt="product_picture" src="items/thumbs/<?=$Item->id?>.jpg"/></a>
	<div class="description"><?=$Item->description?></div>
</div>
<?php endforeach; ?>