<?php foreach($Items AS $Item):?>
<div class="item">
	<h3><a href="view.php?item=<?=$Item->id?>"><?=$Item->name?></a></h3>
	<img alt="product_picture" src="items/thumbs/<?=$Item->id?>.jpg"/>
	<div class="description"><?=$Item->description?></div>
	<h4>Presentaciones:</h4>
	<ul class="options">
		<?php foreach($Item->options AS $option): ?>
		<li><?="{$option['name']}: {$option['description']} ({$option['price']})"?></li>
		<?php endforeach;?>
	</ul>
	<h4>Extras:</h4>
	<ul class="extras">
		<?php foreach($Item->extras AS $extra): ?>
		<li><?="{$extra['name']}: {$extra['description']} ({$extra['price']})"?></li>
		<?php endforeach;?>
	</ul>
</div>
<?php endforeach; ?>