<div class="item_detail">
	<h3><?=$Item->name?></h3>
	<img alt="product_picture" src="items/web/<?=$Item->id?>.jpg"/>
	<div class="description"><?=$Item->description?></div>
	<div class="long_description"><?=nl2br($Item->long_description)?></div>
	<?php if ( count($Item->options) ): ?>
	<h4>Presentaciones:</h4>
	<ul class="options">
		<?php foreach($Item->options AS $option): ?>
		<li><?="{$option['name']}: {$option['description']} ({$option['price']})"?></li>
		<?php endforeach;?>
	</ul>
	<?endif;?>
	<?php if ( count($Item->extras) ): ?>
    	<h4>Extras:</h4>
    	<ul class="extras">
    		<?php foreach($Item->extras AS $extra): ?>
    		<li><?="{$extra['name']}: {$extra['description']} ({$extra['price']})"?></li>
    		<?php endforeach;?>
    	</ul>
    <?endif;?>
   <?php if ($Config->social_display):?>
     <p>
	   <a href="http://twitter.com/share" class="twitter-share-button" data-count="horizontal" data-via="alesibaking" data-related="alesibaking" data-lang="es">Tweet</a><script type="text/javascript" src="http://platform.twitter.com/widgets.js"></script>   
       <iframe src="http://www.facebook.com/plugins/like.php?href=<?=urlencode($Config->system_home)?>v-<?=$Item->id?>&amp;send=true&amp;layout=button_count&amp;width=300&amp;show_faces=false&amp;action=like&amp;colorscheme=light&amp;font&amp;height=21" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:300px; height:21px;" allowTransparency="true"></iframe>
   	 </p>
   <?php endif; ?>
	<div class="clear">
	  <?php if( isset($_SESSION['logged_in']) ):?>
		<a href="edit.php?id=<?=$Item->id?>">Edit</a>
	  <?php endif; ?>	
	</div>
</div>