<?='<?xml version="1.0" encoding="UTF-8"?>'?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title><?=$Config->system_name?></title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <link href="themes/<?=$Config->system_theme?>/style.css" rel="stylesheet" type="text/css" />
    <?php include TO_ROOT . "/themes/$Config->system_theme/headers.phtml"?>
  </head>
  <body>
  	<div class="header">
  	  <h1><a href="<?=$Config->system_home?>"><?=$Config->system_name?></a></h1>
      <?php if (isset($Config->system_slogan)):?>
      	<h2><?=$Config->system_slogan?></h2>
      <?php endif; ?>
      <?php if ($Config->social_display):?>
      <div class="social">
        <ul>
      	  <?php if(isset($Config->social_twitter)):?>
      	  	<li class="twitter"><a href="http://twitter.com/<?=$Config->social_twitter?>" title="Twitter">Twitter</a></li>
      	  <?php endif; ?>
      	  <?php if(isset($Config->social_facebook)):?>	
  		  	<li class="facebook"><a href="http://facebook.com/<?=$Config->social_facebook?>" title="Facebook">Facebook</a></li>
  		  <?php endif; ?>
        </ul>
      </div>
      <?php endif;?>
    </div>
    <?php if(count($Config->top_menu_name) ): ?>
    <div class="top_menu">
    	<ul>
    	<?php
    	  $top_menu_name = $Config->top_menu_name;
    	  foreach($Config->top_menu_url AS $_top_menu_url){ 
    	    list($key,$_top_menu_name) = each($top_menu_name);
    	    ?><li><a href="<?=$_top_menu_url?>"><?=$_top_menu_name?></a></li><?php
    	  }
    	?>	
    	</ul>
    </div>
    <?php endif; ?>
    <div class="content">
      <?= $_template_content_ ?>
    </div>
  	<div class="footer">
      &copy;<?=$Config->system_name . ": "?>
      <?php if (isset($Config->system_slogan)):?>
      	<?=$Config->system_slogan?>
      <?php endif; ?><br/>
      Made with <a href="https://github.com/levhita/ConfigCatalog/">ConfigCatalog</a>.<br/>
	  <?php if( !isset($_SESSION['logged_in']) ){?>
		<a href="login.php">Login</a>
	  <?php } else { ?>
	  	<a href="logout.php">Logout</a> || <a href="admin.php">Admin</a>
	  <?php } ?>
	</div>
    <?php if(count(Logger::getWebLog()) ): ?>    
    <div class="errors">
        <?foreach(Logger::getWebLog() AS $log):?>
        <pre><? print_r($log)?></pre>
        <? endforeach;?>
    </div>
    <?php endif; ?>
  </body>
</html>