<?='<?xml version="1.0" encoding="UTF-8"?>'?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title><?=$Config->system_name?></title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <link href="style/style.css" rel="stylesheet" type="text/css" />
    <link href='http://fonts.googleapis.com/css?family=Cousine:regular,bold' rel='stylesheet' type='text/css' />
    <link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'/>
  </head>
  
  <body>
  	<div class="header">
  	  <h1><a href="<?=$Config->system_home?>"><?=$Config->system_name?></a></h1>
      <h2><?=$Config->system_slogan?></h2>
    </div>
    
    <div class="content">
      <?= $_template_content_ ?>
    </div>
  	
  	<div class="footer">
      &copy;<?=$Config->system_name . ": " . $Config->system_slogan?>.<br/>
      Made with <a href="https://github.com/levhita/ConfigCatalog/">ConfigCatalog</a>.<br/>
	  <?php if( !isset($_SESSION['logged_in']) ){?>
		<a href="login.php">Login</a>
	  <?php } else { ?>
	  	<a href="logout.php">Logout</a> || <a href="admin.php">Admin</a>
	  <?php } ?>
	</div>
    
    <div class="errors">
        <?foreach(Logger::getWebLog() AS $log):?>
        <pre><? print_r($log)?></pre>
        <? endforeach;?>
    </div>
  </body>
</html>